/**
 * API Factory - Creates standardized CRUD operations for REST resources
 *
 * This factory reduces boilerplate by generating common API operations:
 * - list: GET /endpoint (with optional query params)
 * - get: GET /endpoint/:id
 * - create: POST /endpoint
 * - update: PUT /endpoint/:id
 * - delete: DELETE /endpoint/:id
 *
 * Usage:
 * ```ts
 * const horsesApi = createResourceApi<Horse, CreateHorse, UpdateHorse>('/horses');
 *
 * // Use standard operations
 * const horses = await horsesApi.list();
 * const horse = await horsesApi.get(1);
 * const newHorse = await horsesApi.create({ name: 'Spirit' });
 * const updated = await horsesApi.update(1, { name: 'Spirit II' });
 * await horsesApi.delete(1);
 * ```
 */

import axios, { AxiosInstance, AxiosError } from 'axios';

// Get the API base URL
// - In production: use empty string (relative URLs to same host, nginx proxies /api)
// - In development: use localhost:8000 or VITE_API_URL if set
const getApiUrl = (): string => {
  if (import.meta.env.VITE_API_URL) {
    return import.meta.env.VITE_API_URL;
  }
  // In production build, VITE_API_URL is not set - use relative path
  if (import.meta.env.PROD) {
    return '';
  }
  // In development, use same hostname as frontend but with backend port
  if (typeof window !== 'undefined') {
    return `http://${window.location.hostname}:8000`;
  }
  return 'http://localhost:8000';
};

export const API_URL = getApiUrl();

// Re-export axios utilities
export const isAxiosError = axios.isAxiosError;
export type { AxiosError };

// Create the base axios instance
export const apiClient = axios.create({
  baseURL: `${API_URL}/api`,
});

// Add auth interceptor
apiClient.interceptors.request.use((config) => {
  const token = localStorage.getItem('access_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Add token refresh interceptor
apiClient.interceptors.response.use(
  (response) => response,
  async (error) => {
    const originalRequest = error.config;
    if (error.response?.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true;
      const refreshToken = localStorage.getItem('refresh_token');
      if (refreshToken) {
        try {
          const response = await axios.post(`${API_URL}/api/auth/refresh`, null, {
            params: { refresh_token: refreshToken },
          });
          const { access_token, refresh_token } = response.data;
          localStorage.setItem('access_token', access_token);
          localStorage.setItem('refresh_token', refresh_token);
          originalRequest.headers.Authorization = `Bearer ${access_token}`;
          return apiClient(originalRequest);
        } catch {
          localStorage.removeItem('access_token');
          localStorage.removeItem('refresh_token');
          window.location.href = '/';
        }
      }
    }
    return Promise.reject(error);
  }
);

/**
 * Standard CRUD operations generated by the factory
 */
export interface ResourceApi<T, CreateT = Partial<T>, UpdateT = Partial<T>> {
  list: (params?: Record<string, unknown>) => Promise<T[]>;
  get: (id: number) => Promise<T>;
  create: (data: CreateT) => Promise<T>;
  update: (id: number, data: UpdateT) => Promise<T>;
  delete: (id: number) => Promise<void>;
}

/**
 * Creates a standard CRUD API for a resource
 *
 * @param endpoint - The API endpoint (e.g., '/horses')
 * @param client - Optional axios instance (defaults to apiClient)
 */
export function createResourceApi<T, CreateT = Partial<T>, UpdateT = Partial<T>>(
  endpoint: string,
  client: AxiosInstance = apiClient
): ResourceApi<T, CreateT, UpdateT> {
  // Normalize endpoint (ensure leading slash, no trailing slash)
  const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
  const cleanEndpoint = normalizedEndpoint.replace(/\/$/, '');

  return {
    list: async (params?: Record<string, unknown>): Promise<T[]> => {
      const response = await client.get(`${cleanEndpoint}/`, { params });
      return response.data;
    },

    get: async (id: number): Promise<T> => {
      const response = await client.get(`${cleanEndpoint}/${id}`);
      return response.data;
    },

    create: async (data: CreateT): Promise<T> => {
      const response = await client.post(`${cleanEndpoint}/`, data);
      return response.data;
    },

    update: async (id: number, data: UpdateT): Promise<T> => {
      const response = await client.put(`${cleanEndpoint}/${id}`, data);
      return response.data;
    },

    delete: async (id: number): Promise<void> => {
      await client.delete(`${cleanEndpoint}/${id}`);
    },
  };
}

/**
 * Extended API with additional custom operations
 * Use this when you need standard CRUD plus custom endpoints
 */
export function createExtendedApi<
  T,
  CreateT = Partial<T>,
  UpdateT = Partial<T>,
  Extra extends Record<string, unknown> = Record<string, never>
>(
  endpoint: string,
  customOperations: (client: AxiosInstance, basePath: string) => Extra,
  client: AxiosInstance = apiClient
): ResourceApi<T, CreateT, UpdateT> & Extra {
  const baseApi = createResourceApi<T, CreateT, UpdateT>(endpoint, client);
  const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
  const cleanEndpoint = normalizedEndpoint.replace(/\/$/, '');
  const extras = customOperations(client, cleanEndpoint);

  return {
    ...baseApi,
    ...extras,
  };
}

/**
 * Creates a read-only API (no create/update/delete)
 */
export function createReadOnlyApi<T>(
  endpoint: string,
  client: AxiosInstance = apiClient
): Pick<ResourceApi<T>, 'list' | 'get'> {
  const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
  const cleanEndpoint = normalizedEndpoint.replace(/\/$/, '');

  return {
    list: async (params?: Record<string, unknown>): Promise<T[]> => {
      const response = await client.get(`${cleanEndpoint}/`, { params });
      return response.data;
    },

    get: async (id: number): Promise<T> => {
      const response = await client.get(`${cleanEndpoint}/${id}`);
      return response.data;
    },
  };
}

/**
 * Helper for making raw API calls when factory doesn't fit
 */
export const rawApi = {
  get: async <T>(url: string, params?: Record<string, unknown>): Promise<T> => {
    const response = await apiClient.get(url, { params });
    return response.data;
  },

  post: async <T>(url: string, data?: unknown): Promise<T> => {
    const response = await apiClient.post(url, data);
    return response.data;
  },

  put: async <T>(url: string, data?: unknown): Promise<T> => {
    const response = await apiClient.put(url, data);
    return response.data;
  },

  patch: async <T>(url: string, data?: unknown): Promise<T> => {
    const response = await apiClient.patch(url, data);
    return response.data;
  },

  delete: async (url: string): Promise<void> => {
    await apiClient.delete(url);
  },
};

export default apiClient;
